const products = new Map([
  [1, { title: 'Tênis Nike Gamma Force', priceCents: 59999 }],
  [2, { title: 'Nike Zoom Pegasus 40', priceCents: 54999 }],
  [3, { title: 'Camiseta Dri-FIT Pro', priceCents: 14999 }],
  [4, { title: 'Short Training Elite', priceCents: 17999 }],
  [5, { title: 'Blusa de Moletom Masculina adidas Essentials 3 Listras', priceCents: 29999 }],
  [6, { title: 'Calça Feminina Nord Térmica', priceCents: 24999 }],
  [7, { title: 'Tênis Nike Revolution 7 Gs.', priceCents: 27999 }],
  [10, { title: 'Camisa Polo ASICS Racket - Feminina', priceCents: 8999 }],
  [11, { title: 'Tênis Nike Gamma Force - Feminino', priceCents: 69999 }],
  [13, { title: 'New Balance 574 Urban', priceCents: 31999 }],
  [14, { title: 'Camiseta Oversized Graphic', priceCents: 12999 }],
  [15, { title: 'Conjunto Fristyle Fitness Calça Legging com Bolso e Top Academia - Feminino', priceCents: 31999 }],
  [17, { title: 'Tênis adidas Cloud Foam Flex Laces Masculino', priceCents: 45999 }],
  [18, { title: 'Calça Masculina Oxer Elastic', priceCents: 27999 }],
  [19, { title: 'Top Esportivo Strappy', priceCents: 11999 }],
  [20, { title: 'Tênis Masculino Nike Vomero Premium.', priceCents: 38999 }],
  [21, { title: 'Blusão Oxer Moletom Canguru -Masculino', priceCents: 34999 }],
  [22, { title: 'Shorts Ciclista Slim Fem.', priceCents: 13999 }],
  [23, { title: 'Camiseta Básica Premium', priceCents: 7999 }],
  [24, { title: 'Adidas Ultraboost 23', priceCents: 64999 }],
  [25, { title: 'Jaqueta Corta Vendo Barcelona - Masculino', priceCents: 39999 }],
  [27, { title: 'Calça Legging Oxer Campeão Slim - Feminina', priceCents: 19999 }],
  [28, { title: 'Vans Old Skool Pro', priceCents: 24999 }],
  [29, { title: 'Camiseta Cropped Starter Tie Dye - Feminina', priceCents: 10999 }],
  [32, { title: 'Óculos Esportivo UV400', priceCents: 14999 }],
  [33, { title: 'Calça Jogger Masculina Oxer Moletom Bolso', priceCents: 21999 }],
  [34, { title: 'Tenis Puma Wired Run Slip On Ps Bdp Inf', priceCents: 17999 }],
  [35, { title: 'Polo Dry-Fit Premium', priceCents: 15999 }],
  [36, { title: 'Pulseira Esportiva Smart', priceCents: 29999 }],
  [37, { title: 'Jaqueta ASICS Recortes Masculina', priceCents: 32999 }],
  [39, { title: 'Tênis Trail Running GTX', priceCents: 72999 }]
]);

module.exports = products;
